### ISSUE TITLE
Teacher forcing?

### ISSUE THREAD

**Issue by youssefavx** [CookiePPP/cookietts#26]
Hey! I'm really curious how to get Hi-Fi GAN's first step working, would love any help whatsoever but no worries if you aren't free:

```
Generate mel-spectrograms in numpy format using Tacotron2 with teacher-forcing.
The file name of the generated mel-spectrogram should match the audio file and the extension should be .npy.
```

I'm not sure how exactly to do this as specific steps are not specified. Is there some function I need to feed in audio inputs and get out .npy mel spectrograms? 

In searching for 'teacher' I found this function from Tacotron2: https://github.com/NVIDIA/tacotron2/blob/185cd24e046cc1304b4f8e564734d2498c6e2e6f/model.py#L291

Which has the words 'teacher-forced' in it but it's not clear if that will generate the .npy files or not.

**Comment by CookiePPP** [comment]
See
https://github.com/NVIDIA/tacotron2/issues/439#issuecomment-755444725

If you have any problems that might be relevant to that issue then post the problem there and I can link others to it more easily.

**Comment by youssefavx** [comment]
Thank you so much for the help! will do!
