### ISSUE TITLE
Using Bottleneck features

### ISSUE THREAD

**Issue by kannadaraj** [CookiePPP/cookietts#35]
In the hparams file you have mentioned that `use_memory_bottleneck=True,# False baseline`. You have indicated that for training a baseline we should set it to false there by resulting in repetition of axillary features to every spectrogram frame. Just wanted to be sure if i need to set to false for baseline training? Thanks for the help.

**Comment by CookiePPP** [comment]
False would match original tacotron2.
The feature is meant to decrease VRAM usage by mixing the speaker embeddings and torchMoji embeddings in the encoder section of the model and decreasing the dimension of the input to the decoder.

**Comment by kannadaraj** [comment]
Thanks for the comment. Will keep it `true`.
